language: node_js
node_js:
- node
before_install:
- npm install -g gulp
script:
- gulp build --require coffee-script/register
deploy:
  provider: heroku
  api_key:
    secure: o9ZQhAVkjZt/ncJ4SRWJXoNNvBb4zhvCu+QtxmUQd6/vwH/wzDTQJyaw6Ke2Ek9DYETdMIU9sq1BSh0DPYb8s8thirByYTg7MHyaslvBRhohDLAx/d1f/IFXEq8SPU+lsgWazjE3AQ58VLT6LxakugHODBEJ5YwD/wdGACIQk9o=
  app: young-cliffs-7804
  on:
    repo: pgremo/container
